import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={"font-Nunito"}>{children}</body>
    </html>
    //   <html lang="en" className="dark">
    //   <body className={"font-Nunito dark:bg-dark bg-gray-10"}>{children}</body>
    // </html>
  );
}
